# Generated by Django 5.1.1 on 2025-11-27 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0003_remove_unique_together_paciente_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='duracion_atencion_minutos',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='estado_atencion',
            field=models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('EN_ATENCION', 'En Atención'), ('ATENDIDO', 'Atendido')], default='EN_ESPERA', max_length=20),
        ),
        migrations.AddField(
            model_name='cita',
            name='tiempo_fin_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tiempo_inicio_atencion',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='tipo_cita',
            field=models.CharField(choices=[('CONSULTA', 'Consulta'), ('ECOGRAFIA', 'Ecografía')], default='CONSULTA', max_length=20),
        ),
    ]
