# Generated by Django 5.1.1 on 2025-11-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0004_cita_duracion_atencion_minutos_cita_estado_atencion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
