# Generated by Django 5.1.1 on 2025-11-27 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='requiere_ecografia',
            field=models.BooleanField(default=False),
        ),
    ]
