# Generated by Django 5.1.1 on 2025-12-06 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_cita_requiere_ecografia'),
        ('especialidades', '0002_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='comentario_ecografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cita',
            name='especialidad_ecografia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_ecografia', to='especialidades.especialidad'),
        ),
    ]
