# Generated by Django 5.1.1 on 2025-12-14 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_cita_comentario_ecografia_and_more'),
        ('ecografias', '0003_ecografia_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='ecografia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_solicitadas', to='ecografias.ecografia'),
        ),
    ]
