# Generated by Django 5.1.1 on 2025-12-14 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_cita_ecografia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='especialidad_ecografia',
        ),
    ]
