# Generated by Django 5.1.1 on 2025-11-27 12:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0006_alter_medico_especialidad_delete_especialidad'),
        ('especialidades', '0002_alter_especialidad_options_and_more'),
        ('pacientes', '0003_rename_apellidos_paciente_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('estado', models.CharField(choices=[('ACTIVA', 'Activa'), ('INACTIVA', 'Inactiva')], default='ACTIVA', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='especialidades.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecografias', to='accounts.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ecografias', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Ecografía',
                'verbose_name_plural': 'Ecografías',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
