# Generated by Django 5.1.1 on 2025-11-27 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecografias', '0002_remove_ecografia_paciente'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecografia',
            name='nombre',
            field=models.CharField(default='Ecografía', max_length=150),
        ),
    ]
