# Generated by Django 5.1.1 on 2025-12-14 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ecografo'),
        ('ecografias', '0003_ecografia_nombre'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecografia',
            name='medico',
        ),
        migrations.AddField(
            model_name='ecografia',
            name='ecografo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ecografias_asignadas', to='accounts.ecografo'),
            preserve_default=False,
        ),
    ]
