# Generated by Django 4.2.27 on 2025-12-28 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ecografo'),
        ('ecografias', '0004_remove_ecografia_medico_ecografia_ecografo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecografia',
            name='ecografo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ecografias_asignadas', to='accounts.ecografo'),
        ),
    ]
