# Generated by Django 5.2.8 on 2025-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_perfilusuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='apellido_paterno',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='celular',
            field=models.CharField(default='00000000', max_length=15),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ci',
            field=models.CharField(default='Desconocido', max_length=20),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='complemento_ci',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='correo_electronico',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='direccion',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='estado',
            field=models.CharField(choices=[('activo', 'Activo'), ('inactivo', 'Inactivo')], default='activo', max_length=10),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='expedido',
            field=models.CharField(blank=True, choices=[('LP', 'La Paz'), ('SC', 'Santa Cruz'), ('CB', 'Cochabamba'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('BN', 'Beni'), ('PD', 'Pando'), ('CH', 'Chuquisaca')], max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='nombres',
            field=models.CharField(default='Desconocido', max_length=100),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='sexo',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
