# Generated by Django 5.2.8 on 2025-11-22 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_perfilusuario_apellido_materno_and_more'),
        ('horarios', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Admision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventanilla', models.CharField(max_length=20)),
                ('turnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.horariosatencion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admision', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EncargadoAdmision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ventanilla', models.CharField(max_length=20)),
                ('turnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.horariosatencion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='encargado_admision', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Medico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_matricula', models.CharField(max_length=20)),
                ('consultorio', models.CharField(max_length=50)),
                ('dias_atencion', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.diasatencion')),
                ('especialidad', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.especialidad')),
                ('turnos', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.horariosatencion')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_nacimiento', models.DateField()),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1)),
                ('direccion', models.CharField(blank=True, max_length=255, null=True)),
                ('ci', models.CharField(blank=True, max_length=20, null=True)),
                ('complemento_ci', models.CharField(blank=True, max_length=10, null=True)),
                ('expedido', models.CharField(default='CB', max_length=5)),
                ('telefono', models.CharField(blank=True, max_length=15, null=True)),
                ('celular', models.CharField(blank=True, max_length=15, null=True)),
                ('correo', models.EmailField(blank=True, max_length=150, null=True)),
                ('tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.tipousuario')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='PerfilUsuario',
        ),
    ]
