# Generated by Django 5.2.8 on 2025-11-22 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_especialidad_admision_encargadoadmision_medico_and_more'),
        ('especialidades', '0002_alter_especialidad_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='especialidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='especialidades.especialidad'),
        ),
        migrations.DeleteModel(
            name='Especialidad',
        ),
    ]
