# Generated by Django 5.2.8 on 2025-11-28 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_medico_especialidad_delete_especialidad'),
        ('horarios', '0005_turnos_estado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admision',
            name='turnos',
        ),
        migrations.RemoveField(
            model_name='encargadoadmision',
            name='turnos',
        ),
        migrations.RemoveField(
            model_name='medico',
            name='turnos',
        ),
        migrations.AddField(
            model_name='admision',
            name='turnos',
            field=models.ManyToManyField(to='horarios.turnos'),
        ),
        migrations.AddField(
            model_name='encargadoadmision',
            name='turnos',
            field=models.ManyToManyField(to='horarios.turnos'),
        ),
        migrations.AddField(
            model_name='medico',
            name='turnos',
            field=models.ManyToManyField(to='horarios.turnos'),
        ),
    ]
