# Generated by Django 5.1.1 on 2025-12-01 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_admision_turnos_and_more'),
        ('contratos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='contrato',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contratos.contrato'),
        ),
    ]
