# Generated by Django 5.1.1 on 2025-12-13 09:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_perfil_contrato'),
        ('ecografias', '0003_ecografia_nombre'),
        ('horarios', '0006_diasatencion_domingo_diasatencion_sabado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ecografo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_matricula', models.CharField(blank=True, max_length=20)),
                ('consultorio', models.CharField(blank=True, max_length=50)),
                ('dias_atencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='horarios.diasatencion')),
                ('ecografias', models.ManyToManyField(related_name='ecografos', to='ecografias.ecografia')),
                ('turnos', models.ManyToManyField(to='horarios.turnos')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ecografo', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
