# Generated by Django 5.1.1 on 2025-12-06 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_perfil_contrato'),
        ('citas', '0007_cita_comentario_ecografia_and_more'),
        ('especialidades', '0002_alter_especialidad_options_and_more'),
        ('pacientes', '0006_alter_paciente_tipo_seguro'),
    ]

    operations = [
        migrations.CreateModel(
            name='CitaEcografia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('hora', models.TimeField()),
                ('codigo', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('estado', models.CharField(choices=[('PROGRAMADA', 'Programada'), ('CANCELADA', 'Cancelada'), ('REPROGRAMADA', 'Reprogramada'), ('REALIZADA', 'Realizada')], default='PROGRAMADA', max_length=20)),
                ('estado_atencion', models.CharField(choices=[('EN_ESPERA', 'En Espera'), ('EN_ATENCION', 'En Atención'), ('ATENDIDO', 'Atendido')], default='EN_ESPERA', max_length=20)),
                ('tiempo_inicio_atencion', models.DateTimeField(blank=True, null=True)),
                ('tiempo_fin_atencion', models.DateTimeField(blank=True, null=True)),
                ('duracion_atencion_minutos', models.IntegerField(blank=True, null=True)),
                ('comentario_medico', models.TextField(blank=True, null=True)),
                ('resultado_ecografia', models.TextField(blank=True, null=True)),
                ('creada_en', models.DateTimeField(auto_now_add=True)),
                ('actualizada_en', models.DateTimeField(auto_now=True)),
                ('cita_consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='citas_ecografia_generadas', to='citas.cita')),
                ('especialidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_ecografia_medico', to='especialidades.especialidad')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_ecografia', to='accounts.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_ecografia', to='pacientes.paciente')),
            ],
            options={
                'verbose_name': 'Cita de Ecografía',
                'verbose_name_plural': 'Citas de Ecografía',
                'ordering': ['-fecha', '-hora'],
                'constraints': [models.UniqueConstraint(fields=('medico', 'fecha', 'hora'), name='cita_eco_unica_por_medico_slot')],
            },
        ),
    ]
