# Generated by Django 5.1.1 on 2025-12-19 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ecografo'),
        ('citas_ecografia', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citaecografia',
            name='medico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citas_ecografia', to='accounts.ecografo'),
        ),
    ]
