# Generated by Django 5.2.8 on 2025-11-22 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DiasAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lunes', models.BooleanField(default=False)),
                ('martes', models.BooleanField(default=False)),
                ('miercoles', models.BooleanField(default=False)),
                ('jueves', models.BooleanField(default=False)),
                ('viernes', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='HorariosAtencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrugue', models.BooleanField(default=False)),
                ('mannana', models.BooleanField(default=False)),
                ('tarde', models.BooleanField(default=False)),
                ('noche', models.BooleanField(default=False)),
            ],
        ),
    ]
