# Generated by Django 5.2.8 on 2025-11-22 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HorariosAtencion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('madrugue', models.BooleanField(default=False)),
                ('mannana', models.BooleanField(default=False)),
                ('tarde', models.BooleanField(default=False)),
                ('noche', models.BooleanField(default=False)),
            ],
        ),
    ]
