# Generated by Django 5.1.1 on 2025-11-23 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0002_add_horariosatencion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horariosatencion',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
