# Generated by Django 5.2.8 on 2025-11-27 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0004_turnos'),
    ]

    operations = [
        migrations.AddField(
            model_name='turnos',
            name='estado',
            field=models.BooleanField(default=True),
        ),
    ]
