# Generated by Django 5.1.1 on 2025-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horarios', '0005_turnos_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='diasatencion',
            name='domingo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='diasatencion',
            name='sabado',
            field=models.BooleanField(default=False),
        ),
    ]
