# Generated by Django 5.1.1 on 2025-11-17 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='paciente',
            name='emergencia_nombre',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='emergencia_relacion',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='paciente',
            name='emergencia_telefono',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='expedido',
            field=models.CharField(blank=True, choices=[('LP', 'La Paz'), ('SC', 'Santa Cruz'), ('CB', 'Cochabamba'), ('OR', 'Oruro'), ('PT', 'Potosí'), ('TJ', 'Tarija'), ('CH', 'Chuquisaca'), ('BE', 'Beni'), ('PA', 'Pando')], max_length=2),
        ),
        migrations.AddField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino')], max_length=1),
        ),
        migrations.AddField(
            model_name='paciente',
            name='nacionalidad',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_seguro',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='paciente',
            name='tiene_seguro',
            field=models.BooleanField(default=False),
        ),
    ]
