# Generated by Django 5.1.1 on 2025-11-21 09:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0002_paciente_direccion_paciente_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='paciente',
            old_name='apellidos',
            new_name='apellido_paterno',
        ),
        migrations.RenameField(
            model_name='paciente',
            old_name='telefono',
            new_name='celular',
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='apellido_materno',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='calle',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='paciente',
            name='ci_complemento',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_domicilio',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='paciente',
            name='registrado_en',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono_fijo',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='paciente',
            name='zona',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='genero',
            field=models.CharField(blank=True, choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], max_length=1),
        ),
    ]
