# Generated by Django 5.1.1 on 2025-11-28 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0003_rename_apellidos_paciente_apellido_paterno_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='numero_boleta_referencia',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número de Boleta de Referencia (original)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_boleta_sus',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número de Boleta del SUS (original)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_carnet_historial',
            field=models.CharField(blank=True, max_length=60, verbose_name='Número del Carnet de Historial Clínico (Boleta Azul)'),
        ),
        migrations.AddField(
            model_name='paciente',
            name='numero_copias',
            field=models.IntegerField(blank=True, default=0, verbose_name='Número de copias'),
        ),
    ]
