# Generated by Django 5.1.1 on 2025-12-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pacientes', '0004_paciente_numero_boleta_referencia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='tipo_seguro',
            field=models.CharField(blank=True, choices=[('SUS', 'Sistema Único de Salud (SUS)'), ('CNS', 'Caja Nacional de Salud (CNS)'), ('CP', 'Caja Petrolera'), ('SU', 'Seguro Universitario'), ('CSSM', 'Corporación del Seguro Social Militar'), ('CC', 'Caja de Caminos'), ('CBPE', 'Cajas Bancarias Privada y Estatal'), ('OTRO', 'OTRO')], max_length=20),
        ),
    ]
