# Generated by Django 5.1.1 on 2025-12-19 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_ecografo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Modulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('icono', models.CharField(blank=True, help_text='Clase CSS del ícono (ej: fas fa-users)', max_length=50, null=True)),
                ('url', models.CharField(help_text='URL del módulo (ej: /pacientes/)', max_length=200)),
                ('orden', models.IntegerField(default=0, help_text='Orden de aparición en el sidebar')),
                ('activo', models.BooleanField(default=True)),
                ('modulo_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submodulos', to='permisos.modulo')),
            ],
            options={
                'verbose_name': 'Módulo',
                'verbose_name_plural': 'Módulos',
                'ordering': ['orden', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_permiso', models.CharField(choices=[('sin_acceso', 'Sin Acceso'), ('solo_vista', 'Solo Vista'), ('editor', 'Editor')], default='sin_acceso', max_length=20)),
                ('visible', models.BooleanField(default=False, help_text='Si aparece en el sidebar')),
                ('modulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='permisos.modulo')),
                ('tipo_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='accounts.tipousuario')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'unique_together': {('tipo_usuario', 'modulo')},
            },
        ),
    ]
