# Generated by Django 5.1.1 on 2025-12-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_ecografo'),
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ['tipo_usuario', 'modulo__orden'], 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AddField(
            model_name='modulo',
            name='roles_por_defecto',
            field=models.ManyToManyField(blank=True, help_text='Roles que tienen este módulo por defecto', related_name='modulos_por_defecto', to='accounts.tipousuario'),
        ),
    ]
