# Generated by Django 5.1.1 on 2025-12-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_alter_permiso_options_modulo_roles_por_defecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulo',
            name='asignable',
            field=models.BooleanField(default=True, help_text='Si se puede asignar en la gestión de permisos'),
        ),
    ]
